### ISSUE TITLE
DiagnosticOrder specimen searchparameter

### ISSUE THREAD

**Issue by lisney** [fhirbase/fhirbase#89] opened 2015-04-03 13:02 UTC
Query "select fhir.search('DiagnosticOrder', 'specimen=some_existing_code') " returns all resources.
Table "searchparameters" for "DiagnosticOrder" doesn't contain the path "specimen".

**Comment by niquola** [comment] 2015-04-08 16:32
The problem is that some search params from fhir distribution does not have xpath - https://gist.github.com/niquola/9624540b41ef57d13dfa

Gonna fix some of them by hands :(

**Comment by niquola** [comment] 2015-10-30 17:01
Addressed by - https://github.com/fhirbase/fhirbase-plv8/issues/19

**Closed by niquola** 2015-10-30 17:01 UTC
